{% set name = "jazzit" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jazzit-{{ version }}.tar.gz
  sha256: 30c2743583b53fea16a2b8342767f2f4fdec837d59b88f3054289a73a36b92f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - mutagen >=1.45.1
    - playsound >=1.2.2
    - pyfiglet >=0.8.post1
    - python >={{ python_min }}

test:
  imports:
    - jazzit
    - jazzit.jupyter
  requires:
    - ipython
    - python {{ python_min }}

about:
  home: https://github.com/sangarshanan/jazzit
  summary: Enable scripts to play music while running or on erroring out.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
